<a href="https://colab.research.google.com/github/hj-Seong/test/blob/master/ch01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
# pip3 install numpy
# python –m pip3 install numpy

# numpy.py파일이 있는 것을 import하겠다.
import numpy as np

temp1 = [1,2,3,4] # 파이썬 list 8btye 메모리 관리가 안된다
arr1 = np.array(temp1, dtype=np.uint32) #뒤에 크기를 잡아줘야한다. int(16), int32
#dtype 블로그에 정리

print(arr1)
print(type(arr1))
print(arr1.shape) # 차원을 보는 건 콤마



[1 2 3 4]
<class 'numpy.ndarray'>
(4,)


In [13]:
temp2 = 2
arr2 = np.array(temp2)
print(arr2)
print(type(arr2))
print(arr2.shape)


2
<class 'numpy.ndarray'>
()


In [19]:
temp3 = [[1,2,3],[4,5,6],[7,8,9],[10, 11, 12]]
arr3 = np.array(temp3, dtype=np.uint8)
print(arr3)
print(temp3)
print(type(arr3))
print(arr3.shape)
print(arr3.size)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]
<class 'numpy.ndarray'>
(4, 3)
12


In [21]:
temp4 = [
    [[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]],
    [[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]],
    [[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]
]
arr4 = np.array(temp4, dtype=np.uint0)
print(arr4)
print(temp4)
print(type(arr4))
print(arr4.shape)
print(arr4.size)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]

 [[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]

 [[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]]
[[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]], [[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]], [[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]]
<class 'numpy.ndarray'>
(3, 4, 3)
36


In [29]:
temp5 = [
  [1,2,3,4],
  [5,6,7,8]
]

matrix1 = np.array(temp5)
print(matrix1.shape)

re1 = matrix1.reshape((8,))
print(re1)
print("="*50)

re2 = matrix1.reshape((4,2))
print(re2)
print("="*50)

re3 = matrix1.reshape((2,2,2)) # 2*2*2 > 스택으로 쌓인다.
print(re3)
print("="*50)

re4 = matrix1.reshape((1,1,4,2))
print(re4)
print(re4.shape)
print("="*50)


(2, 4)
[1 2 3 4 5 6 7 8]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
[[[[1 2]
   [3 4]
   [5 6]
   [7 8]]]]
(1, 1, 4, 2)


In [36]:
temp6 = [1,2,3,4,5,6]
vector1 = np.array(temp6)
print(vector1)

re1 = vector1.reshape((2,-1)) #-1은 앞의 값을 보고 동적계산
print(re1)

re2 = re1.reshape((-1)) #flattern, flatMap(전개하다) 플랫맵
print(re2)

re3 = re1.flatten()
print(re3)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
[1 2 3 4 5 6]
